# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2fbda37ac3411fe2e140469711b9eb006e8a4507810afabeebef456883bd005e4fcd2cca96895000b0fc9cff4ff98c119691468dae62edc6b224d97f2a31688

test:
  secret_key_base: f7b2e8228c4f79180120347b74cc4dc78021524ff7ec6a0c99351b3034e4d6a1a986755cff7de0fa7873011713207dc0a2b18f255c8cea116d47c4a41e04b32d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
